### ISSUE TITLE
Loading ZipRegex.plist issue

### ISSUE THREAD

**Issue by chaserunner** [Alterplay/APValidators#5]
I use library through CocoaPods.
Trouble when create a path for resource
`
 NSBundle *bundle = [NSBundle bundleForClass:[self class]];
NSString *path = [bundle pathForResource:@"ZipRegex" ofType:@"plist"];
`

Словарь алокейтится пустым. Решил проблему скопировав plist в  основной бандл. Но это костыль. Инвестигейтить в чем проблема не стал. На первый взгляд все должно работать.

**Comment by NickolaySheika** [comment]
Hi

Thank you for your contribution. I've provided update with bug fix. Just update to latest version.
