### ISSUE TITLE
Usage with Swift

### ISSUE THREAD

**Issue by mradzinski** [Alterplay/APValidators#6]
Hi, I've been trying to use this pod in a Swift project of mine but it keeps failing to build. Should I just add APValidator.h class to my bridge header file or also each validator as well?

**Comment by chrisdhaan** [comment]
@mradzinski does you Podfile declare `use_frameworks!`?

I'm able to install APValidators via CocoaPods and use the framework with `import APValidators` in a UIViewController.

**Comment by mradzinski** [comment]
Hey @chrisdhaan, It does include `use_frameworks!`, did you actually add them to your bridging header file?
